"""
embex init — initialize a project for Embex tracking.

Creates .embex/ directory, writes default config, sets up ChromaDB + SQLite,
and runs the initial full-project scan + embed.
"""

from __future__ import annotations

from pathlib import Path

import typer

from embex.config import (
    EmbexConfig,
    create_default_config,
    write_config,
    embex_dir,
    chroma_path,
    history_db_path,
    config_path,
)
from embex.core.embedder import Embedder
from embex.core.vector_store import VectorStore
from embex.core.history_store import HistoryStore
from embex.core.scanner import scan_project
from embex.utils.display import success, error, info


def init_command(
    path: str = typer.Argument(
        ".",
        help="Path to the project root. Defaults to current directory.",
    ),
) -> None:
    """Initialize Embex in a project directory."""
    project_root = Path(path).resolve()

    if not project_root.is_dir():
        error(f"'{project_root}' is not a valid directory.")
        raise typer.Exit(1)

    # Check if already initialised
    if config_path(project_root).exists():
        info("Embex is already initialized in this project.")
        reinit = typer.confirm("Re-scan and re-embed all files?", default=False)
        if not reinit:
            raise typer.Exit(0)

    project_name = project_root.name

    info(f"Initializing Embex in [bold]{project_root}[/bold]")

    # 1. Create .embex/ directory
    dot_embex = embex_dir(project_root)
    dot_embex.mkdir(parents=True, exist_ok=True)

    # 2. Write default config
    config = create_default_config(project_name)
    write_config(project_root, config)
    success("Created embex.json config")

    # 3. Create .gitignore inside .embex/
    gitignore_path = dot_embex / ".gitignore"
    gitignore_path.write_text(
        "# Auto-generated by Embex — ignore local storage\nchroma/\nhistory.db\n",
        encoding="utf-8",
    )
    success("Created .embex/.gitignore")

    # 4. Initialize stores
    try:
        embedder = Embedder(config)
    except EnvironmentError as exc:
        error(str(exc))
        raise typer.Exit(1)

    vector_store = VectorStore(chroma_path(project_root))
    history_store = HistoryStore(history_db_path(project_root))
    success("Initialized ChromaDB and SQLite stores")

    # 5. Full project scan
    info("Scanning project files...")
    result = scan_project(
        project_root=project_root,
        config=config,
        embedder=embedder,
        vector_store=vector_store,
        history_store=history_store,
    )

    history_store.close()

    # Summary
    skipped = result.get("files_skipped", 0)
    skip_note = f", skipped {skipped} unchanged" if skipped else ""
    success(
        f"Done! Processed {result['files_processed']} file(s){skip_note}, "
        f"created {result['chunks_created']} chunk(s)."
    )
    if result["errors"]:
        error(f"{result['errors']} file(s) had errors.")
